#### Back Propogation Using Pytorch

y=x^2

In [ ]:
import torch

In [ ]:
x=torch.tensor(4.0,requires_grad=True)

In [ ]:
x

tensor(4., requires_grad=True)

In [ ]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
#### Back propogation y=2*x
y.backward()

In [ ]:
print(x.grad)

tensor(8.)


In [ ]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input=torch.tensor(lst,requires_grad=True)

In [ ]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [ ]:
### y=x**3+x**2
### y=3x**2+2x--->
y=torch_input**3+torch_input**2

In [ ]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [ ]:
z=y.sum()

In [ ]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [ ]:
z.backward()

In [ ]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])